name: CD-test

on:

  workflow_dispatch:

jobs:
  homolog-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: homolog
      url: "http://homolog.equinox.com.ao"
    steps:
      - name: environment deploy   
        run: echo "environment deploy of ${{vars.environment_deploy}}"

  test:
    runs-on: ubuntu-latest
    environment: 
      name: homolog
      url: "http://homolog.equinox.com.ao"
    needs: [homolog-deploy]
    steps:
      - name: environment deploy   
        run: echo "environment deploy of ${{vars.environment_deploy}}"
        
  production-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: "http://production.equinox.com.ao"
    needs: [test]
    steps:
      - name: environment deploy   
        run: echo "environment deploy of ${{vars.environment_deploy}}"       

