name: CD-test

on:

  workflow_dispatch:

jobs:
  homolog-deploy:
    runs-on: ubuntu-latest
    environment: homolog
    steps:
      - name: environment deploy   
        run: echo "environment deploy of ${{vars.environment_deploy}}"

  test:
    runs-on: ubuntu-latest
    environment: homolog
    needs: [homolog-deploy]
    steps:
      - name: environment deploy   
        run: echo "environment deploy of ${{vars.environment_deploy}}"
        
  production-deploy:
    runs-on: ubuntu-latest
    environment: homolog
    needs: [test]
    steps:
      - name: environment deploy   
        run: echo "environment deploy of ${{vars.environment_deploy}}"       

